name: 'Godot GUT CI'
description: 'Run Godot GUT tests on CI'
branding:
  icon: alert-triangle
  color: gray-dark
inputs:
  godot-version:
    description: 'Godot Version'
    required: false
    default: '3.4.4'
  import-scene:
    description: 'What scene to open while importing assets'
    required: true
  import-time:
    description: 'How long to spend on importing assets'
    required: false
    default: '1'
  test-timeout:
    description: 'The maximum time (in seconds) the tests are allowed to run for'
    required: false
    default: '150'
  project-folder:
    description: 'The folder where the project.godot file is located.'
    required: false
    default: '.'


runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.godot-version }}
    - ${{ inputs.import-scene }}
    - ${{ inputs.import-time }}
    - ${{ inputs.test-timeout }}
    - ${{ inputs.project-folder }}
